# -*- coding: utf-8 -*-
"""Accessing list values.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cZVTA7z9yx5CnVwbEzr_KyUFDtlBanZ_
"""

list = ["aman","khadse","mango",54,54,5,4,5,4]
print(list)

list[-4]

list[5]

list[:5]

list[0:2]

#Advanced slicing

data = 'Aman Khadse 22 2000'
name_slice = slice(0,19)
age_slice = slice(19,21)
salary_slice = slice(22,None)
 
print(data[name_slice])  
print(data[age_slice]) 
print(data[salary_slice])